spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: TRUE
        default_batch_fetch_size: 100
#    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
