spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCLCDB
    username: SHOP_ADMIN
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: TRUE
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
